import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Core surfaces
        surface: "#f7fafc",
        "surface-dim": "#d7dadc",
        "surface-bright": "#f7fafc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f6",
        "surface-container": "#ebeef0",
        "surface-container-high": "#e5e9eb",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "on-surface": "#181c1e",
        "on-surface-variant": "#3d494b",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eef1f3",
        outline: "#6d797b",
        "outline-variant": "#bcc9cb",
        background: "#f7fafc",
        "on-background": "#181c1e",
        // Brand
        primary: "#006671",
        "on-primary": "#ffffff",
        "primary-container": "#00818f",
        "on-primary-container": "#f7feff",
        "primary-fixed": "#97f0ff",
        "primary-fixed-dim": "#66d6e7",
        "on-primary-fixed": "#001f24",
        "on-primary-fixed-variant": "#004f58",
        "inverse-primary": "#66d6e7",
        secondary: "#4a5f80",
        "on-secondary": "#ffffff",
        "secondary-container": "#c3d8ff",
        "on-secondary-container": "#495e7f",
        tertiary: "#006673",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#008091",
        "on-tertiary-container": "#f8feff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        // Custom cleanroom tokens
        "cleanroom-navy": "#0A192F",
        "sterile-surface": "#FFFFFF",
        "clinical-cyan-glow": "#40B5AD",
        "iso-blue": "#008080",
        "spec-border": "#E2E8F0",
        "spec-code-bg": "#E6F4F6",
        "status-sterile": "#00C853",
        "surface-tint": "#006874",
      },
      fontFamily: {
        display: ["var(--font-jakarta)", "system-ui", "sans-serif"],
        heading: ["var(--font-jakarta)", "system-ui", "sans-serif"],
        body: ["var(--font-inter)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        subheading: ["13px", { lineHeight: "18px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "spec-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        margin: "2rem",
        "margin-mobile": "1rem",
        "margin-desktop": "3rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        "space-3xl": "6rem",
      },
      maxWidth: {
        content: "1320px",
      },
      boxShadow: {
        "level-1": "0 4px 16px -2px rgba(11, 35, 65, 0.05), 0 1px 3px 0 rgba(11, 35, 65, 0.03)",
        "level-2": "0 12px 32px -4px rgba(11, 35, 65, 0.08), 0 0 0 1px rgba(0, 151, 167, 0.15)",
        "level-3": "0 24px 48px -8px rgba(10, 25, 47, 0.18), 0 0 24px 0 rgba(0, 172, 193, 0.1)",
        "cyan-glow": "0 4px 14px rgba(0, 151, 167, 0.35)",
        "primary-glow": "0 4px 14px rgba(0, 102, 113, 0.25)",
      },
      keyframes: {
        "marquee": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
      },
      animation: {
        marquee: "marquee 28s linear infinite",
        "float-slow": "float-slow 7s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
